// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oreders.API.Models;

namespace Orders.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190710141451_InitialCreat")]
    partial class InitialCreat
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Oreders.API.Models.Items", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<string>("ItemName");

                    b.Property<int>("UnitsId");

                    b.HasKey("Id");

                    b.HasIndex("UnitsId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Oreders.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int>("TotalAmount");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("Oreders.API.Models.OrderItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<int>("ItemsId");

                    b.Property<int>("OrderId");

                    b.HasKey("Id");

                    b.HasIndex("ItemsId");

                    b.HasIndex("OrderId");

                    b.ToTable("orderItems");
                });

            modelBuilder.Entity("Oreders.API.Models.Units", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("unitName");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Oreders.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSlat");

                    b.Property<string>("Role");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Oreders.API.Models.Items", b =>
                {
                    b.HasOne("Oreders.API.Models.Units", "Units")
                        .WithMany("Items")
                        .HasForeignKey("UnitsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Oreders.API.Models.Order", b =>
                {
                    b.HasOne("Oreders.API.Models.User", "User")
                        .WithMany("orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Oreders.API.Models.OrderItems", b =>
                {
                    b.HasOne("Oreders.API.Models.Items", "Items")
                        .WithMany("OrderItems")
                        .HasForeignKey("ItemsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Oreders.API.Models.Order", "Order")
                        .WithMany("orderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
